Repository getheimdall/heimdall, pull requests merged in 2019-05, with the labels that each got.

#266 Ignored interceptors when select endpoints in front-end
  heimdall-frontend/src/components/interceptors/DnDInterceptor.js
  heimdall-frontend/src/components/interceptors/InterceptorForm.js
  heimdall-frontend/src/containers/Interceptors.js
  heimdall-frontend/src/i18n/en.js
  heimdall-frontend/src/i18n/pt-br.js
  heimdall-frontend/src/styles.less
Labels: release

#258 ClientId and AccessToken headers
  heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/AccessTokenInterceptorService.java
  heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/service/ClientIdInterceptorService.java
Labels: hotfix

#280 Error to create middleware or custom interceptors and edit when already exist a middleware or custom interceptors by front-end
  heimdall-frontend/src/components/interceptors/InterceptorForm.js
  heimdall-frontend/src/utils/InterceptorContentUtils.js
  heimdall-frontend/src/utils/InterceptorUtils.js
Labels: bug

#279 Fixed header.get() method
  heimdall-gateway/src/main/java/br/com/conductor/heimdall/gateway/filter/helper/CallImpl.java
Labels: hotfix

#285 Stringify Content in some interceptors
  heimdall-api/pom.xml
  heimdall-core/pom.xml
  heimdall-frontend/src/utils/InterceptorContentUtils.js
  heimdall-frontend/src/utils/InterceptorUtils.js
  heimdall-gateway/pom.xml
  heimdall-middleware-spec/pom.xml
  pom.xml
Labels: bug, hotfix

#284 Added Unit Tests to Heimdall Core
  heimdall-core/src/test/java/br/com/conductor/heimdall/core/service/EnvironmentServiceTest.java
  heimdall-core/src/test/java/br/com/conductor/heimdall/core/service/PlanServiceTest.java
  heimdall-core/src/test/java/br/com/conductor/heimdall/core/service/ResourceServiceTest.java
Labels: release

#287 Fixed TransientPropertyValueException when updating Interceptor
  heimdall-frontend/src/components/interceptors/InterceptorForm.js
Labels: bug
